name: qbv_browser
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pandas
  - python==3.12.8
  - pytorch
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - flask=3.0.3
  - tqdm
  - pip:
      - pytorch-lightning==1.9.4
      - audioread==3.0.1
      - panns-inference==0.1.1
      - soundfile==0.13.0
